/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        paper: { DEFAULT: '#F4F1EA', 2: '#E8E3D7' },
        ink: { DEFAULT: '#1A1A17', slate: '#3A3D42' },
        graphite: '#6B6E74',
        stamp: '#9B2D20',
        ledger: '#2F5D50',
        ochre: '#B57A1E',
        signal: {
          gaze: '#3E8E7E',
          head: '#5B6BB0',
          audio: '#A8556E',
          tab: '#C08A2E',
        },
        surface: {
          0: 'var(--surface-0)',
          1: 'var(--surface-1)',
          2: 'var(--surface-2)',
        },
        text: {
          primary: 'var(--ink)',
          secondary: 'var(--ink-muted)',
          muted: 'var(--ink-faint)',
          mono: 'var(--cobalt)',
        },
        bg: {
          neutral: 'var(--surface-0)',
          focused: 'var(--surface-1)',
          distracted: 'var(--surface-1)',
          absent: 'var(--surface-1)',
          multi: 'var(--surface-1)',
        },
      },
      fontFamily: {
        display: ['"Archivo Expanded"', '"Archivo Variable"', '"Archivo"', 'system-ui', 'sans-serif'],
        body: ['"Public Sans"', 'system-ui', '-apple-system', 'sans-serif'],
        sans: ['"Public Sans"', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"Space Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
        label: ['"Saira Condensed"', '"Archivo"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1.5' }],
        sm: ['0.875rem', { lineHeight: '1.5' }],
        base: ['1rem', { lineHeight: '1.6' }],
        lg: ['1.125rem', { lineHeight: '1.6' }],
        xl: ['1.375rem', { lineHeight: '1.2', fontWeight: '700' }],
        '2xl': ['1.75rem', { lineHeight: '1.15', fontWeight: '700' }],
        '3xl': ['2.5rem', { lineHeight: '1.05', letterSpacing: '-0.01em', fontWeight: '800' }],
        '4xl': ['3.25rem', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: '800' }],
        '5xl': ['5rem', { lineHeight: '0.95', letterSpacing: '-0.02em', fontWeight: '900' }],
        '6xl': ['5rem', { lineHeight: '0.95', letterSpacing: '-0.02em', fontWeight: '900' }],
        'display-1': ['5rem', { lineHeight: '0.95', letterSpacing: '-0.02em', fontWeight: '900' }],
        'display-2': ['3.25rem', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: '800' }],
        'data-lg': ['2.75rem', { lineHeight: '1' }],
        label: ['0.75rem', { lineHeight: '1.2', letterSpacing: '0.08em' }],
      },
      borderRadius: {
        none: '0',
        DEFAULT: '0',
        sm: '0',
        md: '0',
        lg: '0',
        xl: '0',
        '2xl': '0',
        '3xl': '0',
        full: '9999px',
        'aperture-sm': '0',
        'aperture-md': '0',
        'aperture-lg': '0',
        'aperture-xl': '0',
      },
      borderWidth: {
        3: '3px',
      },
      boxShadow: {
        brutal: '6px 6px 0 0 #1A1A17',
        'brutal-sm': '3px 3px 0 0 #1A1A17',
        'brutal-lg': '10px 10px 0 0 #1A1A17',
        'brutal-red': '6px 6px 0 0 #9B2D20',
        'brutal-paper': '6px 6px 0 0 #F4F1EA',
        'aperture-sm': 'var(--shadow-sm)',
        'aperture-md': 'var(--shadow-md)',
        'aperture-lg': 'var(--shadow-lg)',
        'aperture-xl': 'var(--shadow-xl)',
      },
      transitionTimingFunction: {
        snap: 'cubic-bezier(0.2,0,0,1)',
        stamp: 'cubic-bezier(0.34,1.4,0.64,1)',
      },
    },
  },
  plugins: [],
};
